UBUNTU: SAUCE: rust: allow to use INIT_STACK_ALL_ZERO
BugLink: https://bugs.launchpad.net/bugs/2007654

With CONFIG_INIT_STACK_ALL_ZERO enabled, bindgen passes
-ftrivial-auto-var-init=zero to clang, that triggers the following
error:

 error: '-ftrivial-auto-var-init=zero' hasn't been enabled; enable it at your own peril for benchmarking purpose only with '-enable-trivial-auto-var-init-zero-knowing-it-will-be-removed-from-clang'

However, this additional option that is currently required by clang is
going to be removed in the future (as the name of the option suggests),
with clang-16.

So, make sure bindgen is using this extra option if the major version of
the libclang used by bindgen is < 16.

In this way we can enable CONFIG_INIT_STACK_ALL_ZERO with CONFIG_RUST
without triggering any build error.

Link: https://github.com/llvm/llvm-project/issues/44842
(backported from https://lore.kernel.org/lkml/8178319F-4188-4F8E-AD8D-DCC392E26DBF@kernel.org/T/)
[changed clang-17 -> clang-16 dependency]
Signed-off-by: Andrea Righi <andrea.righi@canonical.com>