powerpc/4xx: Fix warp_gpio_leds build failure
BugLink: https://bugs.launchpad.net/bugs/2060097

[ Upstream commit 5b9e00a6004cf837c43fdb8d5290df619de78024 ]

The 44x/warp_defconfig build fails with:

  arch/powerpc/platforms/44x/warp.c:109:15: error: variable ‘warp_gpio_leds’ has initializer but incomplete type
    109 | static struct platform_device warp_gpio_leds = {
        |               ^~~~~~~~~~~~~~~

Fix it by including platform_device.h.

Fixes: ef175b29a242 ("of: Stop circularly including of_device.h and of_platform.h")
Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
Link: https://msgid.link/20240305123410.3306253-3-mpe@ellerman.id.au
Signed-off-by: Sasha Levin <sashal@kernel.org>
(cherry picked from commit 754a5fc211fb9b1a7c8351f0235d3686ef91944d)
Signed-off-by: Paolo Pisati <paolo.pisati@canonical.com>