NVIDIA: SAUCE: cxl: Fix enum forward declaration
BugLink: https://bugs.launchpad.net/bugs/2169549

This enum can't be forward declared and the build with
aarch64-linux-gnu-gcc 16.1 just fails:

    In file included from ../drivers/pci/probe.c:27:
    ../include/cxl/cxl.h:444:62: error: parameter 2 ('type') has incomplete type
    444 | cxl_find_regblock(struct pci_dev *pdev, enum cxl_regloc_type type,
        |                                         ~~~~~~~~~~~~~~~~~~~~~^~~~
    ../include/cxl/cxl.h:444:1: error: function declaration isn't a prototype [-Werror=strict-prototypes]
    444 | cxl_find_regblock(struct pci_dev *pdev, enum cxl_regloc_type type,
        | ^~~~~~~~~~~~~~~~~
    cc1: some warnings being treated as errors

Replace the forward declaration with the header include.

Cc: Manish Honap <mhonap@nvidia.com>
Fixes: c2905ebe1a66 ("NVIDIA: VR: SAUCE: cxl: Declare cxl_probe_component_regs in public header")
Signed-off-by: Lucas De Marchi <ldemarchi@nvidia.com>