selftests/bpf: Fix const qualifier warning in fexit_bpf2bpf.c
BugLink: https://bugs.launchpad.net/bugs/2154343

Building selftests with
clang 23.0.0 (6fae863eba8a72cdd82f37e7111a46a70be525e0) triggers
the following error:

  tools/testing/selftests/bpf/prog_tests/fexit_bpf2bpf.c:117:12:
  error: assigning to 'char *' from 'const char *' discards qualifiers
  [-Werror,-Wincompatible-pointer-types-discards-qualifiers]

The variable `tgt_name` is declared as `char *`, but it stores the
result of strstr(prog_name[i], "/"). Since `prog_name[i]` is a
`const char *`, the returned pointer should also be treated as
const-qualified.

Update `tgt_name` to `const char *` to match the type of the underlying
string and silence the compiler warning.

Signed-off-by: Varun R Mallya <varunrmallya@gmail.com>
Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
Acked-by: Menglong Dong <menglong.dong@linux.dev>
Link: https://lore.kernel.org/bpf/20260305222132.470700-1-varunrmallya@gmail.com
(cherry picked from commit ca0f39a369c5f927c3d004e63a5a778b08a9df94)
Signed-off-by: Paolo Pisati <paolo.pisati@canonical.com>
Acked-by: Ross Porter <ross.porter@canonical.com>
Acked-by: Changwei Zou <changwei.zou@canonical.com>
Signed-off-by: Mehmet Basaran <mehmet.basaran@canonical.com>