arm_mpam: Fix the build error in resctrl_arch_is_evt_configurable()
Move the declaration of the variable 'cprops' outside of the switch
statement in order to resolve the build error.

mpam_resctrl.c: In function ‘resctrl_arch_is_evt_configurable’:
mpam_resctrl.c:745:3: error: a label can only be part of a statement and a declaration is not a statement
  745 |   struct mpam_props *cprops;
      |   ^~~~~~

Signed-off-by: Shanker Donthineni <sdonthineni@nvidia.com>
Signed-off-by: Tushar Dave <tdave@nvidia.com>
(cherry picked from commit 2aca8a5c8574152fc6a8dbd24c4604f22da4a0fa https://github.com/NVIDIA-BaseOS-6/linux-nvidia-6.5/tree/MPAM-dev)
Signed-off-by: KobaK <kobak@nvidia.com>