NVIDIA: SAUCE: kvm: arm64: Include kvm_emulate.h in kvm/arm_psci.h
Fix a potential build error (like below, when asm/kvm_emulate.h gets
included after the kvm/arm_psci.h) by including the missing header file
in kvm/arm_psci.h:

./include/kvm/arm_psci.h: In function ‘kvm_psci_version’:
./include/kvm/arm_psci.h:29:13: error: implicit declaration of function
   ‘vcpu_has_feature’; did you mean ‘cpu_have_feature’? [-Werror=implicit-function-declaration]
   29 |         if (vcpu_has_feature(vcpu, KVM_ARM_VCPU_PSCI_0_2)) {
	         |             ^~~~~~~~~~~~~~~~
			       |             cpu_have_feature

Change-Id: I8cf97360121200cba0d8d6fc5f54bf08a0a9abf2
Signed-off-by: Suzuki K Poulose <suzuki.poulose@arm.com>
Signed-off-by: Steven Price <steven.price@arm.com>
[cherry-picked: https://lore.kernel.org/all/20241004152804.72508-4-steven.price@arm.com/]
Signed-off-by: Ian May <ianm@nvidia.com>